server:
  port: 8080

spring:
  application:
    name: spring-ai-embedding-model
  ai:
    openai:
      api-key: 123456
      base-url: http://172.17.18.24:8104
      embedding:
        options:
          # 模型ID,需要替换为实际的接入点ID
          model: Qwen3-Embedding-8B
          # Chat接口路径,与OpenAI接口保持一致
          completions-path: /v1/embeddings
