server:
  port: 10003

spring:
  application:
    name: spring-ai-openai-chat
  ai:
    openai:
      api-key: 123456
      base-url: http://172.17.18.24:8106
      chat:
        options:
          # 模型ID,需要替换为实际的接入点ID
          model: Qwen3-Coder-30B-A3B-Instruct
          # Chat接口路径,与OpenAI接口保持一致
          completions-path: /v1/chat/completions